function menu(id,mode) {
  if(mode == "home"){}
    document.getElementById(id).innerHTML="<link href='menu.css' rel='stylesheet'><ul class='topnav'><li><a class='active' href='index.html'>Home</a></li>    <li><a href='account.html'>Mein Account</a></li>      <li><a href='faecher.html'>Fächer</a></li>      <li><a href='download.html'>Download</a></li>      <li><a href='chat.html'>Chatten</a></li>      <li class='right'><form class='' action='index.html' method='post'>        <input type='search' class='search-input' name='' value=''><button type='button' class='search'name='button'>Suchen</button>      </form></li>    </ul>";
  if(mode =="account"){
    document.getElementById(id).innerHTML="<link href='menu.css' rel='stylesheet'><ul class='topnav'><li><a href='index.html'>Home</a></li>    <li><a  class='active' href='account.html'>Mein Account</a></li>      <li><a href='faecher.html'>Fächer</a></li>      <li><a href='download.html'>Download</a></li>      <li><a href='chat.html'>Chatten</a></li>      <li class='right'><form class='' action='index.html' method='post'>        <input type='search' class='search-input' name='' value=''><button type='button' class='search'name='button'>Suchen</button>      </form></li>    </ul>";
  }
  if (mode == "faecher") {
    document.getElementById(id).innerHTML="<link href='menu.css' rel='stylesheet'><ul class='topnav'><li><a href='index.html'>Home</a></li>    <li><a  href='account.html'>Mein Account</a></li>      <li><a class='active' href='faecher.html'>Fächer</a></li>      <li><a href='download.html'>Download</a></li>      <li><a href='chat.html'>Chatten</a></li>      <li class='right'><form class='' action='index.html' method='post'>        <input type='search' class='search-input' name='' value=''><button type='button' class='search'name='button'>Suchen</button>      </form></li>    </ul>";
  }
  if (mode == "Download"){
      document.getElementById(id).innerHTML="<link href='menu.css' rel='stylesheet'><ul class='topnav'><li><a href='index.html'>Home</a></li>    <li><a  href='account.html'>Mein Account</a></li>      <li><a href='faecher.html'>Fächer</a></li>      <li><a  class='active' href='download.html'>Download</a></li>      <li><a href='chat.html'>Chatten</a></li>      <li class='right'><form class='' action='index.html' method='post'>        <input type='search' class='search-input' name='' value=''><button type='button' class='search'name='button'>Suchen</button>      </form></li>    </ul>";}
  if (mode == "Chatten"){
      document.getElementById(id).innerHTML="<link href='menu.css' rel='stylesheet'><ul class='topnav'><li><a href='index.html'>Home</a></li>    <li><a  href='account.html'>Mein Account</a></li>      <li><a href='faecher.html'>Fächer</a></li>      <li><a  href='download.html'>Download</a></li>      <li><a class='active'  href='chat.html'>Chatten</a></li>      <li class='right'><form class='' action='index.html' method='post'>        <input type='search' class='search-input' name='' value=''><button type='button' class='search'name='button'>Suchen</button>      </form></li>    </ul>";}
}
